version: '3.8'
services:
  app:
    container_name: piazza-api
    image: fran15/piazza-api:latest
    restart: always
    ports:
      - 80:3000
    environment:
      DB_CONNECTOR: ${DB_CONNECTOR}
      TOKEN: ${TOKEN}